#!/command/with-contenv bash
# shellcheck shell=bash

# svc-chronyd main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[svc-chronyd] ${line}"; done) 2>&1
    exec /usr/sbin/chronyd -d -m -u chrony
}
main