#!/usr/bin/with-contenv sh

SVC_VERSION="1.0.0"
SLEEP_INTERVAL="${TIMEWATCH_INTERVAL:-60}"

echo "> Timewatch service, version ${SVC_VERSION}, Interval ${SLEEP_INTERVAL}s"

# Delay start
sleep 10

# Run loop
while true; do
  echo "> Timewatch: $(date)"
  sleep "${SLEEP_INTERVAL}"
done
